version: '3.8'
services:
  backend:
    image: node-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    restart: always
